language: node_js
node_js:
  - '10.16.0'

dist: xenial

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - libsecret-1-dev

install:
  - npm ci
  - docker --version
  - docker-compose --version

script:
  - docker-compose up -d
  - sleep 60
  - npm run test
